
server:
  port: 8080

spring:
  application:
    name: travelgo-gateway

cloud:
  gateway:
    routes:
      - id: destinations-service
        uri: http://localhost:8081
        predicates:
          - Path=/api/destinations/**
        filters:
          - StripPrefix=1
