version: '3'

services:
  users-service:
    build: ./users-service
    container_name: users-service
    ports:
      - "8081:8081"

  bookings-service:
    build: ./bookings-service
    container_name: bookings-service
    ports:
      - "8082:8082"

  payments-service:
    build: ./payments-service
    container_name: payments-service
    ports:
      - "8083:8083"
