server:
  port: 8080   

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:

        - id: users-service
          uri: http://users-service:8081
          predicates:
            - Path=/users/**
            - Path=/user/**

        - id: bookings-service
          uri: http://bookings-service:8082
          predicates:
            - Path=/bookings/**
            - Path=/api/trips/**

        - id: payments-service
          uri: http://payments-service:8083
          predicates:
            - Path=/payments/**

management:
  endpoints:
    web:
      exposure:
        include: health,info
